services:
  logger-backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - BACKEND_HOST_URL=0.0.0.0
      - BACKEND_HOST_PORT=3000
    ports:
      - 3000:3000
  logger-frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - 8080:8080
