name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the frontend Docker image
      run: |
        cd frontend
        docker build . --file Dockerfile --tag logger-frontend:$(date +%s)

    - name: Build the backend Docker image
      run: |
        cd backend
        docker build . --file Dockerfile --tag logger-backend:$(date +%s)
