name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker images
      run: |
        docker build . --file frontend/Dockerfile --tag logger-frontend:$(date +%s)
        docker build . --file backend/Dockerfile --tag logger-backend:$(date +%s)
